/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import model.vo.DatosEmpleados;

/**
 *
 * @author usuario
 */
public class ModificacionEmpleadosGUI extends javax.swing.JFrame {

    //Atributos
    
    /**
     * Creates new form ConsultaEmpleadosGUI
     */
    public ModificacionEmpleadosGUI(){
        initComponents();
        
        //No olvidar agregar esto para agregarle las animaciones
        this.setLocationRelativeTo(null);
        this.setTitle("Empleados");
        
    }
    
    
       public String[][] formatoRegistros(ArrayList<DatosEmpleados> consulta, int numeroColumnas){
        
        //Declaración del contenedor de retorno
        String[][] registros = new String[consulta.size()][numeroColumnas];        
        

        //Desenvolver los objetos de la colección
        for (int i = 0; i < consulta.size(); i++) {            
            registros[i][0] = consulta.get(i).getUsuario();
            registros[i][1] = consulta.get(i).getNombre();
            registros[i][2] = consulta.get(i).getNum_cedula();
            registros[i][3] = consulta.get(i).getTelefono();
            registros[i][4] = consulta.get(i).getDireccion();
            registros[i][5] = consulta.get(i).getCiudad();
            registros[i][6] = consulta.get(i).getCargo();
            registros[i][7] = consulta.get(i).getId_sede();
            
        }

        //Retornar registros en formato JTable
        return registros;

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        rbtnId_sede = new javax.swing.JRadioButton();
        rbtnUsuario = new javax.swing.JRadioButton();
        rbtncontrasenia = new javax.swing.JRadioButton();
        rbtnNombre = new javax.swing.JRadioButton();
        rbtnTelefono = new javax.swing.JRadioButton();
        rbtnDireccion = new javax.swing.JRadioButton();
        rbtnCargo = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/team_96px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        titulo.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(153, 153, 153));
        titulo.setText("Seleccione el dato que requiere modificar: ");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Back_64px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 50, 40));

        jLabel3.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setText("Atrás");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, -1, -1));

        titulo1.setFont(new java.awt.Font("Decker", 1, 28)); // NOI18N
        titulo1.setForeground(new java.awt.Color(238, 112, 82));
        titulo1.setText("MODIFICACIÓN DE DATOS DE EMPLEADO");
        jPanel1.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        rbtnId_sede.setBackground(new java.awt.Color(255, 255, 255));
        rbtnId_sede.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        rbtnId_sede.setForeground(new java.awt.Color(238, 112, 82));
        rbtnId_sede.setText("Sede");
        rbtnId_sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnId_sedeActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnId_sede, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        rbtnUsuario.setBackground(new java.awt.Color(255, 255, 255));
        rbtnUsuario.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        rbtnUsuario.setForeground(new java.awt.Color(238, 112, 82));
        rbtnUsuario.setText("Usuario");
        rbtnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnUsuarioMouseClicked(evt);
            }
        });
        rbtnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        rbtncontrasenia.setBackground(new java.awt.Color(255, 255, 255));
        rbtncontrasenia.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        rbtncontrasenia.setForeground(new java.awt.Color(238, 112, 82));
        rbtncontrasenia.setText("Contraseña");
        rbtncontrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtncontraseniaActionPerformed(evt);
            }
        });
        jPanel1.add(rbtncontrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        rbtnNombre.setBackground(new java.awt.Color(255, 255, 255));
        rbtnNombre.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        rbtnNombre.setForeground(new java.awt.Color(238, 112, 82));
        rbtnNombre.setText("Nombre");
        rbtnNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNombreActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        rbtnTelefono.setBackground(new java.awt.Color(255, 255, 255));
        rbtnTelefono.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        rbtnTelefono.setForeground(new java.awt.Color(238, 112, 82));
        rbtnTelefono.setText("Telefono");
        rbtnTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        rbtnDireccion.setBackground(new java.awt.Color(255, 255, 255));
        rbtnDireccion.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        rbtnDireccion.setForeground(new java.awt.Color(238, 112, 82));
        rbtnDireccion.setText("Dirección");
        rbtnDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        rbtnCargo.setBackground(new java.awt.Color(255, 255, 255));
        rbtnCargo.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        rbtnCargo.setForeground(new java.awt.Color(238, 112, 82));
        rbtnCargo.setText("Cargo");
        rbtnCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCargoActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnId_sedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnId_sedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnId_sedeActionPerformed

    private void rbtnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnUsuarioActionPerformed

    private void rbtncontraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtncontraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtncontraseniaActionPerformed

    private void rbtnNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnNombreActionPerformed

    private void rbtnTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnTelefonoActionPerformed

    private void rbtnDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDireccionActionPerformed

    private void rbtnCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnCargoActionPerformed

    private void rbtnUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnUsuarioMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbtnUsuarioMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        ConsultaEmpleadosGUI consulta = new ConsultaEmpleadosGUI();
        consulta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    
    //Aqui en el main es importante cambiar donde dice look and feel, de Nimbus a Windows
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificacionEmpleadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificacionEmpleadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificacionEmpleadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificacionEmpleadosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificacionEmpleadosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton rbtnCargo;
    private javax.swing.JRadioButton rbtnDireccion;
    private javax.swing.JRadioButton rbtnId_sede;
    private javax.swing.JRadioButton rbtnNombre;
    private javax.swing.JRadioButton rbtnTelefono;
    private javax.swing.JRadioButton rbtnUsuario;
    private javax.swing.JRadioButton rbtncontrasenia;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    // End of variables declaration//GEN-END:variables
}
